# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RAPPORT_ANNEE.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QDialog
from RAPPORT_ANNEE import RESUME_ANNEE_LIST


class Ui_RAPPORT_ANNEE(QDialog):
    '''Interface d'utilisateur du Rapport Client'''
    def __init__(self, Dialog):
        super(Ui_RAPPORT_ANNEE, self).__init__(Dialog)
        self.setObjectName("Dialog")
        self.resize(574, 656)
        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setGeometry(QtCore.QRect(210, 600, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel |
                                          QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.treeWidget = QtWidgets.QTreeWidget(self)
        self.treeWidget.setGeometry(QtCore.QRect(20, 50, 361, 511))
        self.treeWidget.setObjectName("treeWidget")
        self.RAL = RESUME_ANNEE_LIST()
        for i in range(0, len(self.RAL.RAL)):
            item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
            QtWidgets.QTreeWidgetItem(item_0)
            QtWidgets.QTreeWidgetItem(item_0)
        self.retranslateUi(self)
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.exec_()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.treeWidget.headerItem().setText(0, _translate(
            "Dialog",
            "Statistique sur les clients"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)

        for i, j in enumerate(self.RAL.RAL):
            self.treeWidget.topLevelItem(i).setText(0, _translate("Dialog",
                                                                  j.YEAR))
            self.treeWidget.topLevelItem(i).child(0).setText(0, _translate(
                "Dialog", "Nb de factures: {}".format(j.N_FACTURE)))
            self.treeWidget.topLevelItem(i).child(1).setText(0, _translate(
                "Dialog", "Montant total: {}".format(j.MONTANT)))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
